name: code_highlight_view
description: Syntax highlighting widget for Flutter. This is an update/fork of package:highlight_view with selectable text and perf improvements.
version: 0.1.0
homepage: https://github.com/1runeberg/code_highlight_view

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
