name: code_highlight_view
description: Syntax highlighting widget for Flutter with lots of languages and themes support.
version: 0.7.0
homepage: https://github.com/git-touch/highlight

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
