name: Test

on: 
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**.md'

  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    name: Test Dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4.1.7
    
    - name: Set up Java
      uses: actions/setup-java@v4.2.2
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2.16.0
      with:
        channel: 'stable'
    
    - name: Quick test
      run: flutter pub get && flutter test
